### ISSUE TITLE
StoredBatchProofOutput type migration in LedgerDb

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#1585]

**Comment by ercecan** [comment]
Talked with @eyusufatik  and decided to go this way:
When extracting outputs from proofs, if deserialization to our current structure (BatchProofCircuitOutput) false we assume this is a pre fork1 proof and deserialize it to StateTransition struct, the output type we use pre fork1, and  convert that to StoredBatchProofOutput instead of StoredStateTransition to store in Ledger DB. There are some additional fields like prev_soft_confirmation_hash, final_soft_confirmation_hash and last_l2_height in the output but since we did not output them before we decided to just set them to zero for pre fork1 proof outputs for rpcs.

With this approach there will be no migration
