### ISSUE TITLE
Prover: Proofs are splittable

### ISSUE THREAD

**Issue by rakanalh** [chainwayxyz/citrea#747]
TBD

**Comment by eyusufatik** [comment]
In our batch proofs, instead of proving all sequencer commitments on a single da block, we can prove a range of sequencer commitments, e.g. first two commitments or last three etc.

This will help us to keep proofs and state diffs under 400kbs. we will have the option to use #744 if there is a single sequencer commitment in a block that yields a diff bigger than 400 kbs as well.

We need inclusion and completeness proof so we'll have to prove it multiple times when we don't prove all commitment proofs in a single proving session, and we'll have to provide all relevant da transactions as inputs to the zk circuit.


TODOs:

- [ ] Add new inputs to the zk circuit, namely sequencer_commitment_start, and sequencer_commitment_end.
- [ ] Verify and run that range of the commitments in the zk guest.
