### ISSUE TITLE
Sequencer commitments should be for L2 range

### ISSUE THREAD

**Issue by rakanalh** [chainwayxyz/citrea#748]
TBD

**Comment by eyusufatik** [comment]
Right now, our sequencer commitments are made for a range of L1 blocks. It includes:
- L1 start hash
- L1 end hash
- Merkle root of soft confirmation hashes of L2 blocks that was built in this range.

With upcoming updates it will be very helpful to commit to L2 ranges.

So the commitments should include:
- L2 start height
- L2 end height
- Merkle root of soft confirmations in this range (inclusive)

TODOs:

- [ ] Update LedgerDB tables accordingly.
- [ ] Update postgres tables accordingly.
- [ ] Keep the logic of when to commit the same, it will be changed after this PR.
- [ ] Update our `run_sequencer_commitments_in_da_slot` function with the necessary changes but don't delete stuff, just comment out.
- [ ] Update tests, since the logic for when to commit is the same not much should change, only the asserts we compare l1 start hashes etc.
