### ISSUE TITLE
Consolidate commitment logic

### ISSUE THREAD

**Issue by rakanalh** [chainwayxyz/citrea#856]
Based on a conversation with @eyusufatik and as a follow up to #739 

> right now in this pr it’s either over 300kb or (when we are finished with an L1 block and there is more commitments than min_soft_confirmations_per_commitment )
> we’ll need to remove any logic, ledger and postgres stuff related to L1 on this “when to commit” logic then we are fine
> over 300kb or non-committed is over min_soft_confirmations_per_commitment no more crazy L1 stuff

**Comment by eyusufatik** [comment]
I think only thing to do is just removing depending on last committed L1 height.

So our commit or not logic would just be: 

```
If we've reached over 300kb 

or 

If we have not commmitted for more than `min_soft_confirmation_per_commitment`
```
 
This would simplify all of `crates/sequencer/src/commitment_controller.rs` and some parts of `crates/sequencer/src/sequencer.rs` a lot.

So TODOs:

- [ ] Removing dependency on L1 related stuff in our commit/don't commit logic and controller.
- [ ] Removing last committed l1 height table, and code where it's used.
- [ ] This might affect some tests because with the new logic the sequencer might commit before the test expects :). But should be fairly easy to fix.
- [ ] Simplify tests, we would not need the "publish L2, publish L1, publish L2" logic anymore
