### ISSUE TITLE
Revisit L1 fee calculation

### ISSUE THREAD

**Issue by yaziciahmet** [chainwayxyz/citrea#979]
There seems to be some potential problems with our L1 fee calculation. Think, test, and improve it, potentially calculate things by hand and compare accordingly.

This issue is born from the pr #973 . When revm is updated, the l1 fee has changed, causing doubts about the calculation about the l1 fee calculation. Keep in mind about the cases where revm was in the wrong. One thing I observed is that previously, even 0 value caused a BalanceTransfer journal to be emitted, while in the new version it doesn't.

**Comment by ercecan** [comment]
Turns out there was a problem in `revm` that resulted in a `storage change event` even if the account is **warm loaded** in `sload`,
now it is fixed, the storage change will still happen if and only if the account is cold loaded
It is fixed in this pr in v37,  our current implementation remains correct
https://github.com/bluealloy/revm/pull/1437
